 class MultipleCatch2
{
public static void main(String args[])
{
try
{
String s=null;
s.length();
}
catch(ArithmeticException e)
{
System.out.println("task1 is completed");
}
catch(ArrayIndexOutOfBoundsException e)
{
System.out.println("task2 completed");
}
catch (Exception e)
{
System.out.println("common task completed");
}
System.out.println("rest of the code");
}
}
